from __future__ import annotations

import base64
import json
import os
import re
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

from agents import Agent, Runner
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.concurrency import run_in_threadpool
from fastapi.middleware.cors import CORSMiddleware
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from openai import OpenAI
from pydantic import BaseModel, Field

load_dotenv()

DEFAULT_MODEL = os.getenv("OPENAI_MODEL", "gpt-5-mini")
AUTOFILL_MODEL = os.getenv("OPENAI_AUTOFILL_MODEL", DEFAULT_MODEL)
EMAIL_PATTERN = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
SCOPES = ["https://www.googleapis.com/auth/gmail.send"]
CREDENTIALS_FILE = Path("credentials.json")
TOKEN_FILE = Path("token.json")


class OutreachEmail(BaseModel):
    subject: str = Field(min_length=5, max_length=90)
    body_text: str = Field(min_length=80)


class OutreachRequest(BaseModel):
    sender_name: str = Field(min_length=1)
    sender_company: str | None = None
    recipient_name: str = Field(min_length=1)
    recipient_email: str = Field(min_length=3)
    recipient_company: str | None = None
    topic: str = Field(min_length=3)
    value_proposition: str = Field(min_length=10)
    personalization: str | None = None
    call_to_action: str | None = None


class SendEmailRequest(BaseModel):
    recipient_email: str = Field(min_length=3)
    subject: str = Field(min_length=1, max_length=120)
    body_text: str = Field(min_length=1)


class SendEmailResponse(BaseModel):
    status: str
    message_id: str


class AIAutofillRequest(BaseModel):
    input: str = Field(min_length=1)


class AIAutofillResponse(BaseModel):
    topic: str = Field(min_length=1)
    value_proposition: str = Field(min_length=1)
    personalization: str = Field(min_length=1)
    cta: str = Field(min_length=1)


def validate_email_address(value: str, field_name: str) -> str:
    candidate = value.strip()
    if not EMAIL_PATTERN.match(candidate):
        raise ValueError(f"{field_name} must be a valid email address.")
    return candidate


def ensure_openai_config() -> str:
    openai_api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not openai_api_key:
        raise ValueError("Missing required environment variable: OPENAI_API_KEY")
    return os.getenv("OPENAI_MODEL", DEFAULT_MODEL).strip() or DEFAULT_MODEL


def get_openai_client() -> OpenAI:
    openai_api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not openai_api_key:
        raise ValueError("Missing required environment variable: OPENAI_API_KEY")
    return OpenAI(api_key=openai_api_key)


def build_agent(model: str) -> Agent[Any]:
    instructions = """
You are writing an outreach email for a SaaS product called ReachForge.

ReachForge is an AI-powered tool that helps users generate professional outreach emails instantly from a simple input.

Users describe what they want, and the platform generates high-quality emails automatically.

You are NOT selling a template, document, or offer letter.
You are promoting a software tool that enables this.

Write a concise outreach email that reflects a real SaaS product pitch.

Rules:
- Keep the email body between 150 and 250 words.
- Use a natural, human tone.
- Avoid generic filler phrases.
- Focus on ease, speed, automation, and practical value.
- Make it clear that ReachForge helps users generate emails quickly from a short input.
- Never position the offer as a template, document, downloadable file, or one-off deliverable.
- Do not include any meta commentary such as "generated by ReachForge", "created with AI", "powered by AI", or any P.S. disclosure about the tool.
- The subject line must sound like a real SaaS outreach subject line.
- Return valid structured output only.
""".strip()

    return Agent(
        name="Professional Outreach Agent",
        instructions=instructions,
        output_type=OutreachEmail,
        model=model,
    )


def build_generation_prompt(request: OutreachRequest) -> str:
    return (
        "Write an outreach email using the following inputs.\n\n"
        f"Topic: {request.topic}\n"
        f"Value Proposition: {request.value_proposition}\n"
        f"Personalization: {request.personalization or 'None provided'}\n"
        f"CTA: {request.call_to_action or 'Invite the recipient to a short conversation'}\n\n"
        "Return a strong SaaS-style subject line and an email body.\n"
        "The email body must be at least 150 words and no more than 250 words.\n"
        "The email body must promote ReachForge as an AI-powered tool that helps users generate outreach emails instantly from a simple input.\n"
        "Do not describe or imply the offer is a template, document, or downloadable file.\n"
        "Do not add any footer, P.S., disclaimer, or note saying the email was generated by ReachForge or AI.\n"
    )


def extract_json_object(content: str) -> dict[str, Any]:
    raw_content = content.strip()
    if not raw_content:
        raise ValueError("OpenAI returned an empty response.")

    try:
        parsed = json.loads(raw_content)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*\}", raw_content, re.DOTALL)
    if not match:
        raise ValueError("OpenAI did not return valid JSON.")

    try:
        parsed = json.loads(match.group(0))
    except json.JSONDecodeError as exc:
        raise ValueError("OpenAI returned invalid JSON.") from exc

    if not isinstance(parsed, dict):
        raise ValueError("OpenAI returned malformed JSON.")

    return parsed


def generate_ai_autofill(user_input: str) -> AIAutofillResponse:
    client = get_openai_client()
    completion = client.chat.completions.create(
        model=AUTOFILL_MODEL,
        response_format={"type": "json_object"},
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an AI outreach assistant. Convert the user input into JSON with:\n"
                    "topic, value_proposition, personalization, cta.\n"
                    "Assume the user is using a SaaS tool that generates outreach emails, not selling templates or documents.\n"
                    "Return only JSON."
                ),
            },
            {
                "role": "user",
                "content": user_input,
            },
        ],
    )

    response_text = completion.choices[0].message.content or ""
    payload = extract_json_object(response_text)
    return AIAutofillResponse.model_validate(payload)


def generate_email(request: OutreachRequest, model: str | None = None) -> OutreachEmail:
    selected_model = model or ensure_openai_config()
    request.recipient_email = validate_email_address(request.recipient_email, "recipient_email")

    agent = build_agent(selected_model)
    result = Runner.run_sync(agent, build_generation_prompt(request))
    draft = result.final_output

    if not isinstance(draft, OutreachEmail):
        raise RuntimeError("The agent did not return a valid outreach email.")

    return draft


def authenticate_gmail(
    credentials_path: Path = CREDENTIALS_FILE,
    token_path: Path = TOKEN_FILE,
):
    if not credentials_path.exists():
        raise FileNotFoundError(
            f"Missing {credentials_path}. Download the OAuth desktop app credentials from Google Cloud and place the file next to this script."
        )

    creds: Credentials | None = None
    if token_path.exists():
        creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(str(credentials_path), SCOPES)
            creds = flow.run_local_server(port=0)

        token_path.write_text(creds.to_json())

    return build("gmail", "v1", credentials=creds)


def create_gmail_message(recipient_email: str, subject: str, message_body: str) -> dict[str, str]:
    message = MIMEText(message_body, "plain", "utf-8")
    message["to"] = validate_email_address(recipient_email, "recipient_email")
    message["subject"] = subject

    encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode("utf-8")
    return {"raw": encoded_message}


def send_email(recipient_email: str, subject: str, message_body: str) -> str:
    service = authenticate_gmail()
    gmail_message = create_gmail_message(recipient_email, subject, message_body)

    try:
        response = (
            service.users()
            .messages()
            .send(userId="me", body=gmail_message)
            .execute()
        )
    except HttpError as exc:
        raise RuntimeError(f"Gmail API failed to send the email: {exc}") from exc

    return response["id"]


app = FastAPI(
    title="Outreach Agent API",
    description="Generate personalized outreach emails with OpenAI and send them with the Gmail API.",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def read_root() -> dict[str, str]:
    return {"status": "ok", "message": "Outreach Agent API is running."}


@app.post("/generate-email", response_model=OutreachEmail)
def generate_email_endpoint(request: OutreachRequest) -> OutreachEmail:
    try:
        return generate_email(request)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/api/ai-autofill", response_model=AIAutofillResponse)
async def ai_autofill_endpoint(request: AIAutofillRequest) -> AIAutofillResponse:
    try:
        return await run_in_threadpool(generate_ai_autofill, request.input)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/send-email", response_model=SendEmailResponse)
def send_email_endpoint(request: SendEmailRequest) -> SendEmailResponse:
    try:
        message_id = send_email(
            recipient_email=request.recipient_email,
            subject=request.subject,
            message_body=request.body_text,
        )
        return SendEmailResponse(status="success", message_id=message_id)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
